/* SO1G2000 Sample */
/* 05-24-2010 : 17:34:30 */

/* This file is automatically generated by OneTouch Studio */
/* This file is very specific to a design */

/* ****************************************** */
/* ****************************************** */
/* ==> WARNING: ** DO NOT EDIT This file <==  */
/* ****************************************** */
/* ****************************************** */

#ifdef      OT_LIB_VER_4_ABOVE
                    /* NOTE: For OTLib 4.0 or above */

#ifndef _OTCONFIG_H
#define _OTCONFIG_H

#define OT_ADDR                         0x2C    /* OneTouch Device I2C Slave Address */

/* OneTouch Register Definitions */

#define OT_CONFIG_REG_START_ADDR        0x0000
#define OT_CONFIG_REG_END_ADDR          0x0018
#define OT_NUM_CONFIG_REG_BYTES         ((OT_CONFIG_REG_END_ADDR - OT_CONFIG_REG_START_ADDR + 1)*2)
                                    /* Total number of Configuration Bytes */

#define OT_DATA_REG_START_ADDR          0x0106
#define OT_DATA_REG_END_ADDR            0x0109
#define OT_NUM_DATA_REG_BYTES           ((OT_DATA_REG_END_ADDR - OT_DATA_REG_START_ADDR + 1)*2)
                                    /* Total number of Data Bytes */

#define OT_DATA_REG_START_ADDR_HIGH     ((OT_DATA_REG_START_ADDR & 0xFF00)>>8)
#define OT_DATA_REG_START_ADDR_LOW      (OT_DATA_REG_START_ADDR & 0x00FF)


#define OT_BUTTON_DATA_REG_OFFSET       6
#define OT_BUTTON_HIGH_ELECTRODE        4
#define OT_BUTTON_LOW_ELECTRODE         15


#define OT_GPI_DATA_REG_OFFSET            4
#define OT_GPI_HIGH_ELECTRODE             1
#define OT_GPI_LOW_ELECTRODE              4


#define OT_STRIP1_DATA_REG_OFFSET       0


#define OT_CONFIG_TABLE_ROWS            13

static u8 OT_Config_Table[OT_CONFIG_TABLE_ROWS][4] = {
/* {address-high-byte, address-low-byte, data-hi-byte, data-lo-byte } */
{ 0x00, 0x00, 0x00, 0x07 },
{ 0x00, 0x01, 0x00, 0x00 },
{ 0x00, 0x02, 0x00, 0x32 },
{ 0x00, 0x04, 0xB0, 0xD0 },
{ 0x00, 0x08, 0x02, 0x0D },
{ 0x00, 0x0F, 0x02, 0x00 },
{ 0x00, 0x10, 0x00, 0xA1 },
{ 0x00, 0x11, 0x9D, 0xA7 },
{ 0x00, 0x12, 0x00, 0x9A },
{ 0x00, 0x13, 0x9F, 0x91 },
{ 0x00, 0x14, 0x8D, 0x00 },
{ 0x00, 0x16, 0x92, 0x92 },
{ 0x00, 0x17, 0x9D, 0x00 },
{ 0x00, 0x0E, 0x1E, 0x01 }
};

#endif

#else
            /* NOTE: For OTLib 3.0 or earlier */

#ifndef _SYNAOTCONFIG_H
#define _SYNAOTCONFIG_H

#include "justin_kr_synaptics_keytouch.h"
#include "justin_kr_synaptics_user.h"

#define OT_ADDR                         0x2C    /* OneTouch Device I2C Slave Address */

/* OneTouch Register Definitions */

#define OT_CONFIG_REG_START_ADDR        0x0000
#define OT_CONFIG_REG_END_ADDR          0x0018
#define OT_NUM_CONFIG_REG_BYTES         ((OT_CONFIG_REG_END_ADDR - OT_CONFIG_REG_START_ADDR + 1)*2)
                                        /* Total number of Configuration Bytes */
#define OT_NUM_CONFIG_BYTES             37//(OT_NUM_CONFIG_REG_BYTES + 2)

#if 0
static OT_U8    g_OT_Config[OT_NUM_CONFIG_BYTES]= {

                    /* High byte, followed by low Byte */
    //0x00,
    0x00,     /* base address of config registers */
    0x00, 0x07,     /* values of 0x0000 */
    0x00, 0x00,     /* values of 0x0001 */
    0x00, 0x00,     /* values of 0x0002 */
    0x00, 0x00,     /* values of 0x0003 */
    0x00, 0x05,     /* values of 0x0004 */
    0x00, 0x00,     /* values of 0x0005 */
    0x00, 0x00,     /* values of 0x0006 */
    0x00, 0x00,     /* values of 0x0007 */
    0x00, 0x00,     /* values of 0x0008 */
    0x00, 0x00,     /* values of 0x0009 */
    0x00, 0x00,     /* values of 0x000A */
    0x00, 0x00,     /* values of 0x000B */
    0x00, 0x00,     /* values of 0x000C */
    0x00, 0x00,     /* values of 0x000D */
    0x00, 0x00,     /* values of 0x000E */
    0x00, 0x00,     /* values of 0x000F */
    0xAA, 0xAA,     /* values of 0x0010 */
    0xAA, 0xAA,     /* values of 0x0011 */

#endif

#if 0
	// High byte, followed by low Byte
	//0x00, 0x00,		// base address of config registers
	0x00, 0x07,		// values of 0x0000
	0x00, 0x00,		// values of 0x0001
	0x00, 0x00,		// values of 0x0002
	0x00, 0x00,		// values of 0x0003
	0x00, 0x09,		// values of 0x0004
	0x00, 0x00,		// values of 0x0005
	0x00, 0x00,		// values of 0x0006
	0x00, 0x00,		// values of 0x0007
	0x00, 0x00,		// values of 0x0008
	0x00, 0x00,		// values of 0x0009
	0x00, 0x00,		// values of 0x000A
	0x00, 0x00,		// values of 0x000B
	0x00, 0x00,		// values of 0x000C
	0x00, 0x00,		// values of 0x000D
	0x00, 0x00,		// values of 0x000E
	0x00, 0x00,		// values of 0x000F
	0x00, 0xFF,		// values of 0x0010
	0xFF, 0x00,		// values of 0x0011
	0x00, 0x00,		// values of 0x0012
	0x00, 0x00,		// values of 0x0013
	0x00, 0x00,		// values of 0x0014
	0x00, 0x00,		// values of 0x0015
	0x00, 0x00,		// values of 0x0016
	0x00, 0x00,		// values of 0x0017
	0x00, 0x00,		// values of 0x0018
	0x00, 0x00,		// values of 0x0019
	0x00, 0x00,		// values of 0x001A
	0x00, 0x00,		// values of 0x001B
	0x00, 0x00,		// values of 0x001C
	0x00, 0x00,		// values of 0x001D
	0x00, 0x00,		// values of 0x001E
	0x00, 0x00,		// values of 0x001F
	0x00, 0x00,		// values of 0x0020
	0x00, 0x00,		// values of 0x0021
	0x00, 0x00,		// values of 0x0022
	0x00, 0x00,		// values of 0x0023
	0x00, 0x00,		// values of 0x0024
	0x00, 0x00		// values of 0x0025

};
#endif
#endif
#endif

