obj-$(CONFIG_BJ_PROXI_SENSOR)		+= bj_proximity.o
obj-$(CONFIG_BJ_COMPASS_SENSOR)		+= akm8973.o
obj-$(CONFIG_BJ_KXTF9_SENSOR)		+= kxtf9.o kxtf9_if.o kionix_accel_api.o
obj-$(CONFIG_BJ_MPU3050_SENSOR)		+= mpu3050.o
obj-$(CONFIG_BJ_MOTION_SENSOR)		+= bj_motion.o
