#
# Makefile for the TDMB FC8050 drivers.
#

# Each configuration option enables a list of files.
# LGE
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= broadcast_fc8050_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= broadcast_fc8050.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= tdmb_tunerbbdrv_fc8050.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= bbm.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= fc8050_bb.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= fc8050_demux.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= fc8050_hpi.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= fc8050_i2c.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= fc8050_isr.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= fc8050_ppi.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= fc8050_spi.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= fc8050_tun.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= fci_hal.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= fci_i2c.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= fci_oal.o
obj-$(CONFIG_LGE_BROADCAST_TDMB)	+= fci_tun.o
#obj-y		+= broadcast_fc8050_drv_if.o
#obj-y		+= broadcast_fc8050.o
#obj-y		+= tdmb_tunerbbdrv_fc8050.o
#obj-y		+= bbm.o
#obj-y		+= fc8050_bb.o
#obj-y		+= fc8050_demux.o
#obj-y		+= fc8050_hpi.o
#obj-y		+= fc8050_i2c.o
#obj-y		+= fc8050_isr.o
#obj-y		+= fc8050_ppi.o
#obj-y		+= fc8050_spi.o
#obj-y		+= fc8050_tun.o
#obj-y		+= fci_hal.o
#obj-y		+= fci_i2c.o
#obj-y		+= fci_oal.o
#obj-y		+= fci_tun.o
