# MUIC Class Driver
obj-$(CONFIG_MUIC)		+= muic_class.o muic_client_class.o

obj-$(CONFIG_DP3T)		+= dp3t.o
obj-$(CONFIG_USIF)		+= usif.o

obj-$(CONFIG_MUIC_TS5USBA33402) += lu6800_muic.o
obj-$(CONFIG_MUIC_TSU5611) += muic_tsu5611.o
obj-$(CONFIG_MUIC_MAX14526DEEWP)          += ku5900_muic.o


